# Generated by Django 6.0.7 on 2026-08-30 21:07

import django.db.models.deletion
import themes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "装扮目录版本",
                "verbose_name_plural": "装扮目录版本",
            },
        ),
        migrations.CreateModel(
            name="DecorationItem",
            fields=[
                (
                    "decoration_id",
                    models.SlugField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=80)),
                ("desc", models.TextField(blank=True)),
                ("cover_img", models.CharField(default="default", max_length=255)),
                ("detail_img", models.CharField(blank=True, max_length=255)),
                ("poster_img", models.CharField(blank=True, max_length=255)),
                ("style_json", models.JSONField(blank=True, default=dict)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("nav_bar", "导航栏"),
                            ("tab_bar", "底部Tab栏"),
                            ("button", "交互按钮"),
                            ("card", "罐头卡片"),
                            ("home_bg", "个人主页背景"),
                            ("avatar_frame", "头像框"),
                            ("comment_bubble", "评论气泡"),
                            ("topic_card", "话题卡片"),
                            ("input_box", "弹窗输入框"),
                        ],
                        max_length=32,
                    ),
                ),
                ("group", models.CharField(blank=True, max_length=64)),
                ("style_tags", models.JSONField(blank=True, default=list)),
                ("dialect_tags", models.JSONField(blank=True, default=list)),
                (
                    "privilege_type",
                    models.CharField(
                        choices=[
                            ("free", "免费"),
                            ("member", "会员专属"),
                            ("activity", "活动限定"),
                            ("creator", "方言创作者专属"),
                        ],
                        default="free",
                        max_length=16,
                    ),
                ),
                ("get_condition", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可用"),
                            ("coming", "待上线"),
                            ("deprecated", "已下架绝版"),
                        ],
                        default="coming",
                        max_length=16,
                    ),
                ),
                (
                    "support_terminal",
                    models.JSONField(default=themes.models.default_terminals),
                ),
                ("activity_start_at", models.DateTimeField(blank=True, null=True)),
                ("activity_end_at", models.DateTimeField(blank=True, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("collect_count", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "局部装扮",
                "verbose_name_plural": "局部装扮",
                "ordering": ["component_type", "decoration_id"],
            },
        ),
        migrations.CreateModel(
            name="ThemeItem",
            fields=[
                (
                    "theme_id",
                    models.SlugField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=80)),
                ("desc", models.TextField(blank=True)),
                ("cover_img", models.CharField(default="default", max_length=255)),
                ("detail_img", models.CharField(blank=True, max_length=255)),
                ("poster_img", models.CharField(blank=True, max_length=255)),
                ("style_json", models.JSONField(blank=True, default=dict)),
                ("style_tags", models.JSONField(blank=True, default=list)),
                ("dialect_tags", models.JSONField(blank=True, default=list)),
                (
                    "privilege_type",
                    models.CharField(
                        choices=[
                            ("free", "免费"),
                            ("member", "会员专属"),
                            ("activity", "活动限定"),
                            ("creator", "方言创作者专属"),
                        ],
                        default="free",
                        max_length=16,
                    ),
                ),
                ("get_condition", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可用"),
                            ("coming", "待上线"),
                            ("deprecated", "已下架绝版"),
                        ],
                        default="coming",
                        max_length=16,
                    ),
                ),
                (
                    "support_terminal",
                    models.JSONField(default=themes.models.default_terminals),
                ),
                ("activity_start_at", models.DateTimeField(blank=True, null=True)),
                ("activity_end_at", models.DateTimeField(blank=True, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("collect_count", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "全局主题",
                "verbose_name_plural": "全局主题",
                "ordering": ["-create_time", "theme_id"],
            },
        ),
        migrations.CreateModel(
            name="UserThemeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("global_theme_id", models.CharField(default="default", max_length=64)),
                ("decoration_map", models.JSONField(blank=True, default=dict)),
                ("is_cover_local_decoration", models.BooleanField(default=True)),
                ("recent_use_list", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "当前装扮配置",
                "verbose_name_plural": "当前装扮配置",
            },
        ),
        migrations.CreateModel(
            name="UserThemeEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_member", models.BooleanField(default=False)),
                ("creator_unlocked", models.BooleanField(default=False)),
                ("activity_ids", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_entitlement",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "装扮权益",
                "verbose_name_plural": "装扮权益",
            },
        ),
        migrations.CreateModel(
            name="ThemeEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitor_id", models.CharField(blank=True, max_length=64)),
                ("event_name", models.CharField(max_length=64)),
                ("item_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theme_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "装扮行为事件",
                "verbose_name_plural": "装扮行为事件",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_name", "item_id", "created_at"],
                        name="themes_them_user_id_0344b7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserThemeCollect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("theme", "全局主题"), ("decoration", "局部装扮")],
                        max_length=16,
                    ),
                ),
                ("item_id", models.CharField(max_length=64)),
                ("collect_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_collects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "装扮收藏",
                "verbose_name_plural": "装扮收藏",
                "ordering": ["-collect_time"],
                "unique_together": {("user", "item_type", "item_id")},
            },
        ),
        migrations.CreateModel(
            name="UserThemeMix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mix_id", models.SlugField(max_length=64)),
                ("mix_name", models.CharField(max_length=20)),
                ("global_theme_id", models.CharField(default="default", max_length=64)),
                ("decoration_map", models.JSONField(blank=True, default=dict)),
                ("decoration_ids", models.JSONField(blank=True, default=list)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_mixes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "历史搭配",
                "verbose_name_plural": "历史搭配",
                "ordering": ["-create_time"],
                "unique_together": {("user", "mix_id")},
            },
        ),
    ]
