from .models import ComponentType, ItemStatus, PrivilegeType

THEMES = [
    {
        "theme_id": "default",
        "name": "默认方言主题",
        "desc": "乡野松绿｜统一导航、按钮和卡片配色",
        "cover_img": "default",
        "style_json": {
            "accent": "pine",
            "primaryLook": "fill",
            "ghostLook": "line",
            "effect": "none",
        },
        "style_tags": ["简约"],
        "dialect_tags": [],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "paper",
        "name": "素白纸本",
        "desc": "田野笔记｜浅底细线、留白克制",
        "cover_img": "simple",
        "style_json": {
            "accent": "pine",
            "primaryLook": "outline",
            "ghostLook": "line",
            "effect": "none",
        },
        "style_tags": ["简约"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "mistpad",
        "name": "雾青便笺",
        "desc": "浅雾便签｜软底清透",
        "cover_img": "simple",
        "style_json": {
            "accent": "mist",
            "primaryLook": "soft",
            "ghostLook": "fog",
            "effect": "none",
        },
        "style_tags": ["简约"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "member-pine",
        "name": "松风会员",
        "desc": "会员专属｜松绿细纹",
        "cover_img": "simple",
        "style_json": {"accent": "pine", "primaryLook": "fill"},
        "style_tags": ["简约"],
        "privilege_type": PrivilegeType.MEMBER,
        "get_condition": "开通会员后可启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "event-lantern",
        "name": "同乡灯会",
        "desc": "活动限定｜同乡灯火",
        "cover_img": "street",
        "style_json": {"accent": "clay", "effect": "none"},
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.ACTIVITY,
        "get_condition": "限时同乡灯会产出",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "event-spring",
        "name": "开春乡音",
        "desc": "活动已结束｜已绝版",
        "cover_img": "festival",
        "style_json": {"accent": "clay"},
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.ACTIVITY,
        "get_condition": "活动已结束",
        "status": ItemStatus.DEPRECATED,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "creator-tile",
        "name": "方言达人青瓦",
        "desc": "创作者专属｜青瓦细纹",
        "cover_img": "guofeng",
        "style_json": {"accent": "pine"},
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.CREATOR,
        "get_condition": "完成方言创作任务后领取",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "chuankiang",
        "name": "川渝烟火",
        "desc": "巴蜀市井热辣风格",
        "cover_img": "dialect",
        "style_json": {"accent": "clay"},
        "style_tags": ["地域方言风"],
        "dialect_tags": ["川渝"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "敬请期待",
        "status": ItemStatus.COMING,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "wuyu",
        "name": "江南吴语",
        "desc": "水乡青墨｜浅波纹与雾青水洗",
        "cover_img": "simple",
        "style_json": {
            "accent": "mist",
            "primaryLook": "wash",
            "ghostLook": "fog",
            "effect": "none",
        },
        "style_tags": ["地域方言风"],
        "dialect_tags": ["江南吴语"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "yue",
        "name": "岭南粤韵",
        "desc": "骑楼朱印｜砖红满洲窗",
        "cover_img": "festival",
        "style_json": {
            "accent": "clay",
            "primaryLook": "seal",
            "ghostLook": "seal",
            "effect": "glow",
        },
        "style_tags": ["地域方言风"],
        "dialect_tags": ["岭南粤韵"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "minnan",
        "name": "闽台闽南",
        "desc": "盐田暖金｜海岛桂色",
        "cover_img": "dialect",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "fill",
            "ghostLook": "fresh",
            "effect": "lift",
        },
        "style_tags": ["地域方言风"],
        "dialect_tags": ["闽台闽南"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "mimeograph",
        "name": "油印乡刊",
        "desc": "旧刊栏线｜茶褐油墨与纸边",
        "cover_img": "retro",
        "style_json": {
            "accent": "tea",
            "primaryLook": "classic",
            "ghostLook": "classic",
            "effect": "ink",
        },
        "style_tags": ["复古"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "teaslip",
        "name": "茶褐笺",
        "desc": "书房茶渍｜细线笺纸",
        "cover_img": "retro",
        "style_json": {
            "accent": "tea",
            "primaryLook": "outline",
            "ghostLook": "quiet",
            "effect": "none",
        },
        "style_tags": ["复古"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "ledger",
        "name": "乡账旧册",
        "desc": "账册栏线｜陶土深沉",
        "cover_img": "retro",
        "style_json": {
            "accent": "clay",
            "primaryLook": "solemn",
            "ghostLook": "solemn",
            "effect": "none",
        },
        "style_tags": ["复古"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "nightferry",
        "name": "夜航电台",
        "desc": "夜航网格｜青墨指示灯",
        "cover_img": "cyber",
        "style_json": {
            "accent": "ink",
            "primaryLook": "contrast",
            "ghostLook": "gilt",
            "effect": "glow",
        },
        "style_tags": ["赛博"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "signalbooth",
        "name": "讯号亭",
        "desc": "冷青指示灯｜赛博岗亭",
        "cover_img": "cyber",
        "style_json": {
            "accent": "mist",
            "primaryLook": "fill",
            "ghostLook": "filled",
            "effect": "pulse",
        },
        "style_tags": ["赛博"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "gridlamp",
        "name": "网格航灯",
        "desc": "航灯散光｜金线网格",
        "cover_img": "cyber",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "gilt",
            "ghostLook": "gilt",
            "effect": "bloom",
        },
        "style_tags": ["赛博"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "qingshan",
        "name": "青绿山水",
        "desc": "青绿层峦｜松绿描边留白",
        "cover_img": "guofeng",
        "style_json": {
            "accent": "pine",
            "primaryLook": "outline",
            "ghostLook": "wash",
            "effect": "none",
        },
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "sealpaper",
        "name": "朱印宣纸",
        "desc": "朱印方章｜宣纸栏",
        "cover_img": "guofeng",
        "style_json": {
            "accent": "clay",
            "primaryLook": "seal",
            "ghostLook": "seal",
            "effect": "glow",
        },
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "inkscroll",
        "name": "水墨长卷",
        "desc": "墨洗长卷｜晕墨留白",
        "cover_img": "guofeng",
        "style_json": {
            "accent": "ink",
            "primaryLook": "wash",
            "ghostLook": "wash",
            "effect": "ink",
        },
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "teahouse",
        "name": "茶馆木栏",
        "desc": "木栏茶座｜茶褐热络",
        "cover_img": "street",
        "style_json": {
            "accent": "tea",
            "primaryLook": "ardent",
            "ghostLook": "ardent",
            "effect": "lift",
        },
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "nightstall",
        "name": "夜市灯牌",
        "desc": "街沿灯火｜暖牌光晕",
        "cover_img": "street",
        "style_json": {
            "accent": "clay",
            "primaryLook": "fill",
            "ghostLook": "ardent",
            "effect": "glow",
        },
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "lanternalley",
        "name": "巷口灯笼",
        "desc": "灯笼散光｜桂金巷口",
        "cover_img": "street",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "soft",
            "ghostLook": "ardent",
            "effect": "bloom",
        },
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "midautumn",
        "name": "中秋桂影",
        "desc": "桂金圆窗｜中秋听罐头",
        "cover_img": "festival",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "gilt",
            "ghostLook": "gilt",
            "effect": "gilt",
        },
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "duanwu",
        "name": "端午蒲艾",
        "desc": "蒲艾青绿｜清新时节",
        "cover_img": "festival",
        "style_json": {
            "accent": "pine",
            "primaryLook": "fresh",
            "ghostLook": "fresh",
            "effect": "none",
        },
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "lanternyear",
        "name": "岁灯",
        "desc": "年节灯火｜朱印散光",
        "cover_img": "festival",
        "style_json": {
            "accent": "clay",
            "primaryLook": "seal",
            "ghostLook": "seal",
            "effect": "bloom",
        },
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "pixelbooth",
        "name": "像素广播亭",
        "desc": "像素格子｜清新播音亭",
        "cover_img": "anime",
        "style_json": {
            "accent": "mist",
            "primaryLook": "fresh",
            "ghostLook": "filled",
            "effect": "pulse",
        },
        "style_tags": ["二次元"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "starglyph",
        "name": "星符乡音",
        "desc": "星符金边｜浅星点",
        "cover_img": "anime",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "gilt",
            "ghostLook": "gilt",
            "effect": "glow",
        },
        "style_tags": ["二次元"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "comicstrip",
        "name": "格子漫页",
        "desc": "漫画分格｜按压弹跳",
        "cover_img": "anime",
        "style_json": {
            "accent": "clay",
            "primaryLook": "fill",
            "ghostLook": "filled",
            "effect": "press",
        },
        "style_tags": ["二次元"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "inknight",
        "name": "墨夜极简",
        "desc": "深底细线｜极简暗色",
        "cover_img": "dark",
        "style_json": {
            "accent": "ink",
            "primaryLook": "solemn",
            "ghostLook": "quiet",
            "effect": "none",
        },
        "style_tags": ["极简暗色"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "voidgrid",
        "name": "空格暗网",
        "desc": "暗网细格｜雾青对比",
        "cover_img": "dark",
        "style_json": {
            "accent": "mist",
            "primaryLook": "contrast",
            "ghostLook": "quiet",
            "effect": "none",
        },
        "style_tags": ["极简暗色"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "coalnook",
        "name": "炭火暗角",
        "desc": "暖暗炭火｜薄雾茶褐",
        "cover_img": "dark",
        "style_json": {
            "accent": "tea",
            "primaryLook": "fog",
            "ghostLook": "fog",
            "effect": "none",
        },
        "style_tags": ["极简暗色"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
]


DECORATIONS = [
    {
        "decoration_id": "cards-plain",
        "name": "系统默认罐头卡",
        "desc": "罐头卡片跟随当前主题。",
        "cover_img": "cards",
        "style_json": {"borderRadius": "12px"},
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-plain",
        "name": "系统默认主页底",
        "desc": "个人主页背景跟随当前主题。",
        "cover_img": "profile",
        "style_json": {"background": "var(--page-color)"},
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-plain",
        "name": "系统默认头像框",
        "desc": "头像不加额外边框。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "0px"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-bubble-plain",
        "name": "系统默认评论气泡",
        "desc": "评论气泡跟随当前主题。",
        "cover_img": "comment",
        "style_json": {"borderRadius": "12px"},
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-paper",
        "name": "宣纸折边",
        "desc": "罐头卡片带宣纸折边和浅阴影。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "4px",
            "borderColor": "var(--border-color)",
            "shadow": "0 8rpx 20rpx var(--border-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-mist",
        "name": "江雾纹理",
        "desc": "个人中心底换成一层淡雾。",
        "cover_img": "profile",
        "style_json": {"background": "var(--surface-subtle-color)"},
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-frame",
        "name": "青瓦圆框",
        "desc": "头像外加一圈主题色青瓦框。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "4px", "borderColor": "var(--accent-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-paper",
        "name": "宣纸气泡",
        "desc": "评论气泡像一小张宣纸。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "4px",
            "background": "var(--surface-color)",
            "borderColor": "var(--border-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-brick",
        "name": "红砖压纹",
        "desc": "罐头卡片底带浅砖纹和陶土细边。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "2px",
            "borderWidth": "2px",
            "borderColor": "var(--accent-color)",
            "background": "var(--surface-subtle-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-round",
        "name": "软圆罐头卡",
        "desc": "罐头卡片收成更圆的软边。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "24px",
            "shadow": "0 12rpx 24rpx var(--border-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-night",
        "name": "夜航网格",
        "desc": "个人中心底换成夜航网格。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--surface-color)",
            "color": "var(--text-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-grain",
        "name": "田野浅纹",
        "desc": "个人中心底带一层浅田野纹。",
        "cover_img": "profile",
        "style_json": {"background": "var(--accent-subtle-color)"},
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-glyph",
        "name": "方言文字框",
        "desc": "头像框带一圈方言字。",
        "cover_img": "avatar",
        "style_json": {
            "borderWidth": "2px",
            "borderColor": "var(--accent-color)",
            "color": "var(--accent-color)",
        },
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-ink",
        "name": "青墨细框",
        "desc": "头像外加一圈青墨细线。",
        "cover_img": "avatar",
        "style_json": {
            "borderWidth": "6px",
            "borderColor": "var(--text-color)",
        },
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-round",
        "name": "软圆气泡",
        "desc": "评论气泡收成更圆的软边。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "24px",
            "background": "var(--surface-subtle-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-ink",
        "name": "青墨方泡",
        "desc": "评论气泡换成青墨细方框。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "0px",
            "borderColor": "var(--text-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "navbar-plain",
        "name": "系统默认顶栏",
        "desc": "导航栏跟随当前主题。小程序原生栏无法自定义。",
        "cover_img": "nav",
        "style_json": {"color": "var(--text-color)"},
        "component_type": ComponentType.NAV_BAR,
        "group": "navbar",
        "style_tags": ["导航栏"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5"],
    },
    {
        "decoration_id": "tabbar-plain",
        "name": "系统默认底栏",
        "desc": "底部 Tab 跟随当前主题。小程序原生栏无法自定义。",
        "cover_img": "tabbar",
        "style_json": {"background": "var(--surface-color)"},
        "component_type": ComponentType.TAB_BAR,
        "group": "tabbar",
        "style_tags": ["底部Tab"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5"],
    },
    {
        "decoration_id": "cards-member",
        "name": "会员宣纸卡",
        "desc": "会员专属罐头卡片纹理。",
        "cover_img": "cards",
        "style_json": {"borderColor": "var(--accent-color)"},
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.MEMBER,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-creator",
        "name": "方言达人头像框",
        "desc": "完成创作任务后领取。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "4px"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.CREATOR,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
]


def seed_catalog():
    from .models import CatalogVersion, DecorationItem, ThemeItem

    for row in THEMES:
        ThemeItem.objects.update_or_create(theme_id=row["theme_id"], defaults=row)
    for row in DECORATIONS:
        DecorationItem.objects.update_or_create(
            decoration_id=row["decoration_id"], defaults=row
        )
    CatalogVersion.objects.get_or_create(pk=1, defaults={"value": 1})
