from .models import ComponentType, ItemStatus, PrivilegeType


def free_theme(
    theme_id,
    name,
    desc,
    cover,
    accent,
    primary,
    ghost,
    effect,
    style_tag,
    dialect_tags=None,
):
    row = {
        "theme_id": theme_id,
        "name": name,
        "desc": desc,
        "cover_img": cover,
        "style_json": {
            "accent": accent,
            "primaryLook": primary,
            "ghostLook": ghost,
            "effect": effect,
        },
        "style_tags": [style_tag],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    }
    if dialect_tags:
        row["dialect_tags"] = dialect_tags
    return row


THEMES = [
    {
        "theme_id": "default",
        "name": "默认方言主题",
        "desc": "乡野松绿｜统一导航、按钮和卡片配色",
        "cover_img": "default",
        "style_json": {
            "accent": "pine",
            "primaryLook": "fill",
            "ghostLook": "line",
            "effect": "none",
        },
        "style_tags": ["简约"],
        "dialect_tags": [],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "paper",
        "name": "素白纸本",
        "desc": "田野笔记｜浅底细线、留白克制",
        "cover_img": "simple",
        "style_json": {
            "accent": "pine",
            "primaryLook": "outline",
            "ghostLook": "line",
            "effect": "none",
        },
        "style_tags": ["简约"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "mistpad",
        "name": "雾青便笺",
        "desc": "浅雾便签｜软底清透",
        "cover_img": "simple",
        "style_json": {
            "accent": "mist",
            "primaryLook": "soft",
            "ghostLook": "fog",
            "effect": "none",
        },
        "style_tags": ["简约"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "member-pine",
        "name": "松风会员",
        "desc": "会员专属｜松绿细纹",
        "cover_img": "simple",
        "style_json": {"accent": "pine", "primaryLook": "fill"},
        "style_tags": ["简约"],
        "privilege_type": PrivilegeType.MEMBER,
        "get_condition": "开通会员后可启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "event-lantern",
        "name": "同乡灯会",
        "desc": "活动限定｜同乡灯火",
        "cover_img": "street",
        "style_json": {"accent": "clay", "effect": "none"},
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.ACTIVITY,
        "get_condition": "限时同乡灯会产出",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "event-spring",
        "name": "开春乡音",
        "desc": "活动已结束｜已绝版",
        "cover_img": "festival",
        "style_json": {"accent": "clay"},
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.ACTIVITY,
        "get_condition": "活动已结束",
        "status": ItemStatus.DEPRECATED,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "creator-tile",
        "name": "方言达人青瓦",
        "desc": "创作者专属｜青瓦细纹",
        "cover_img": "guofeng",
        "style_json": {"accent": "pine"},
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.CREATOR,
        "get_condition": "完成方言创作任务后领取",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "chuankiang",
        "name": "川渝烟火",
        "desc": "巴蜀市井热辣风格",
        "cover_img": "dialect",
        "style_json": {"accent": "clay"},
        "style_tags": ["地域方言风"],
        "dialect_tags": ["川渝"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "敬请期待",
        "status": ItemStatus.COMING,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "wuyu",
        "name": "江南吴语",
        "desc": "水乡青墨｜浅波纹与雾青水洗",
        "cover_img": "simple",
        "style_json": {
            "accent": "mist",
            "primaryLook": "wash",
            "ghostLook": "fog",
            "effect": "none",
        },
        "style_tags": ["地域方言风"],
        "dialect_tags": ["江南吴语"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "yue",
        "name": "岭南粤韵",
        "desc": "骑楼朱印｜砖红满洲窗",
        "cover_img": "festival",
        "style_json": {
            "accent": "clay",
            "primaryLook": "seal",
            "ghostLook": "seal",
            "effect": "glow",
        },
        "style_tags": ["地域方言风"],
        "dialect_tags": ["岭南粤韵"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "minnan",
        "name": "闽台闽南",
        "desc": "盐田暖金｜海岛桂色",
        "cover_img": "dialect",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "fill",
            "ghostLook": "fresh",
            "effect": "lift",
        },
        "style_tags": ["地域方言风"],
        "dialect_tags": ["闽台闽南"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "mimeograph",
        "name": "油印乡刊",
        "desc": "旧刊栏线｜茶褐油墨与纸边",
        "cover_img": "retro",
        "style_json": {
            "accent": "tea",
            "primaryLook": "classic",
            "ghostLook": "classic",
            "effect": "ink",
        },
        "style_tags": ["复古"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "teaslip",
        "name": "茶褐笺",
        "desc": "书房茶渍｜细线笺纸",
        "cover_img": "retro",
        "style_json": {
            "accent": "tea",
            "primaryLook": "outline",
            "ghostLook": "quiet",
            "effect": "none",
        },
        "style_tags": ["复古"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "ledger",
        "name": "乡账旧册",
        "desc": "账册栏线｜陶土深沉",
        "cover_img": "retro",
        "style_json": {
            "accent": "clay",
            "primaryLook": "solemn",
            "ghostLook": "solemn",
            "effect": "none",
        },
        "style_tags": ["复古"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "nightferry",
        "name": "夜航电台",
        "desc": "夜航网格｜青墨指示灯",
        "cover_img": "cyber",
        "style_json": {
            "accent": "ink",
            "primaryLook": "contrast",
            "ghostLook": "gilt",
            "effect": "glow",
        },
        "style_tags": ["赛博"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "signalbooth",
        "name": "讯号亭",
        "desc": "冷青指示灯｜赛博岗亭",
        "cover_img": "cyber",
        "style_json": {
            "accent": "mist",
            "primaryLook": "fill",
            "ghostLook": "filled",
            "effect": "pulse",
        },
        "style_tags": ["赛博"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "gridlamp",
        "name": "网格航灯",
        "desc": "航灯散光｜金线网格",
        "cover_img": "cyber",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "gilt",
            "ghostLook": "gilt",
            "effect": "bloom",
        },
        "style_tags": ["赛博"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "qingshan",
        "name": "青绿山水",
        "desc": "青绿层峦｜松绿描边留白",
        "cover_img": "guofeng",
        "style_json": {
            "accent": "pine",
            "primaryLook": "outline",
            "ghostLook": "wash",
            "effect": "none",
        },
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "sealpaper",
        "name": "朱印宣纸",
        "desc": "朱印方章｜宣纸栏",
        "cover_img": "guofeng",
        "style_json": {
            "accent": "clay",
            "primaryLook": "seal",
            "ghostLook": "seal",
            "effect": "glow",
        },
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "inkscroll",
        "name": "水墨长卷",
        "desc": "墨洗长卷｜晕墨留白",
        "cover_img": "guofeng",
        "style_json": {
            "accent": "ink",
            "primaryLook": "wash",
            "ghostLook": "wash",
            "effect": "ink",
        },
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "teahouse",
        "name": "茶馆木栏",
        "desc": "木栏茶座｜茶褐热络",
        "cover_img": "street",
        "style_json": {
            "accent": "tea",
            "primaryLook": "ardent",
            "ghostLook": "ardent",
            "effect": "lift",
        },
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "nightstall",
        "name": "夜市灯牌",
        "desc": "街沿灯火｜暖牌光晕",
        "cover_img": "street",
        "style_json": {
            "accent": "clay",
            "primaryLook": "fill",
            "ghostLook": "ardent",
            "effect": "glow",
        },
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "lanternalley",
        "name": "巷口灯笼",
        "desc": "灯笼散光｜桂金巷口",
        "cover_img": "street",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "soft",
            "ghostLook": "ardent",
            "effect": "bloom",
        },
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "midautumn",
        "name": "中秋桂影",
        "desc": "桂金圆窗｜中秋听罐头",
        "cover_img": "festival",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "gilt",
            "ghostLook": "gilt",
            "effect": "gilt",
        },
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "duanwu",
        "name": "端午蒲艾",
        "desc": "蒲艾青绿｜清新时节",
        "cover_img": "festival",
        "style_json": {
            "accent": "pine",
            "primaryLook": "fresh",
            "ghostLook": "fresh",
            "effect": "none",
        },
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "lanternyear",
        "name": "岁灯",
        "desc": "年节灯火｜朱印散光",
        "cover_img": "festival",
        "style_json": {
            "accent": "clay",
            "primaryLook": "seal",
            "ghostLook": "seal",
            "effect": "bloom",
        },
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "pixelbooth",
        "name": "像素广播亭",
        "desc": "像素格子｜清新播音亭",
        "cover_img": "anime",
        "style_json": {
            "accent": "mist",
            "primaryLook": "fresh",
            "ghostLook": "filled",
            "effect": "pulse",
        },
        "style_tags": ["二次元"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "starglyph",
        "name": "星符乡音",
        "desc": "星符金边｜浅星点",
        "cover_img": "anime",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "gilt",
            "ghostLook": "gilt",
            "effect": "glow",
        },
        "style_tags": ["二次元"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "comicstrip",
        "name": "格子漫页",
        "desc": "漫画分格｜按压弹跳",
        "cover_img": "anime",
        "style_json": {
            "accent": "clay",
            "primaryLook": "fill",
            "ghostLook": "filled",
            "effect": "press",
        },
        "style_tags": ["二次元"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "inknight",
        "name": "墨夜极简",
        "desc": "深底细线｜极简暗色",
        "cover_img": "dark",
        "style_json": {
            "accent": "ink",
            "primaryLook": "solemn",
            "ghostLook": "quiet",
            "effect": "none",
        },
        "style_tags": ["极简暗色"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "voidgrid",
        "name": "空格暗网",
        "desc": "暗网细格｜雾青对比",
        "cover_img": "dark",
        "style_json": {
            "accent": "mist",
            "primaryLook": "contrast",
            "ghostLook": "quiet",
            "effect": "none",
        },
        "style_tags": ["极简暗色"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "coalnook",
        "name": "炭火暗角",
        "desc": "暖暗炭火｜薄雾茶褐",
        "cover_img": "dark",
        "style_json": {
            "accent": "tea",
            "primaryLook": "fog",
            "ghostLook": "fog",
            "effect": "none",
        },
        "style_tags": ["极简暗色"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
]

THEMES += [
    free_theme("inkline", "青墨细栏", "青墨栏线｜细线克制", "simple", "ink", "outline", "line", "none", "简约"),
    free_theme("claypad", "陶土浅笺", "陶土便签｜浅底留白", "simple", "clay", "soft", "quiet", "none", "简约"),
    free_theme("teanote", "茶雾便条", "茶褐薄雾｜浅底便签", "simple", "tea", "soft", "fog", "none", "简约"),
    free_theme("fieldfresh", "田野清新", "松绿清透｜微微浮起", "simple", "pine", "fresh", "fresh", "lift", "简约"),
    free_theme("mistfill", "雾青实心", "雾青实键｜细线辅色", "simple", "mist", "fill", "line", "none", "简约"),
    free_theme("giltedge", "桂金细线", "桂金描边｜克制金边", "simple", "osmanthus", "outline", "gilt", "none", "简约"),
    free_theme("wuyubridge", "吴语石桥", "石桥苔痕｜浅底水洗", "simple", "mist", "soft", "wash", "none", "地域方言风", ["江南吴语"]),
    free_theme("wuyurain", "吴语夜雨", "夜雨晕墨｜青墨水洗", "simple", "ink", "wash", "fog", "ink", "地域方言风", ["江南吴语"]),
    free_theme("yueporch", "粤韵廊檐", "廊檐细线｜陶土印框", "festival", "clay", "outline", "seal", "none", "地域方言风", ["岭南粤韵"]),
    free_theme("yuewindow", "满洲金窗", "满洲窗金｜朱印浅光", "festival", "osmanthus", "seal", "gilt", "glow", "地域方言风", ["岭南粤韵"]),
    free_theme("minnanharbor", "闽南渡口", "渡口清透｜雾青实心", "dialect", "mist", "fill", "fresh", "none", "地域方言风", ["闽台闽南"]),
    free_theme("minnantemple", "闽南庙金", "庙宇金线｜陶土古风", "dialect", "clay", "classic", "seal", "gilt", "地域方言风", ["闽台闽南"]),
    free_theme("oldnews", "旧报栏", "旧报栏线｜青墨古风", "retro", "ink", "classic", "classic", "none", "复古"),
    free_theme("kilnslip", "窑褐笺", "窑褐细线｜深沉留白", "retro", "clay", "outline", "solemn", "none", "复古"),
    free_theme("teapress", "茶印旧刊", "茶褐实心｜按压旧刊", "retro", "tea", "fill", "classic", "press", "复古"),
    free_theme("rustwash", "锈迹水洗", "锈褐水洗｜晕墨旧痕", "retro", "tea", "wash", "quiet", "ink", "复古"),
    free_theme("ledgergold", "账册金线", "账册深沉｜桂金细框", "retro", "osmanthus", "solemn", "gilt", "none", "复古"),
    free_theme("mistclassic", "青灰旧栏", "青灰古风｜细线旧栏", "retro", "mist", "classic", "line", "none", "复古"),
    free_theme("nightgrid", "夜网岗", "夜网实心｜呼吸指示灯", "cyber", "ink", "fill", "quiet", "pulse", "赛博"),
    free_theme("coldlamp", "冷青航灯", "冷青描边｜航灯光晕", "cyber", "mist", "outline", "gilt", "glow", "赛博"),
    free_theme("coppernet", "铜网讯号", "铜网对比｜散光讯号", "cyber", "clay", "contrast", "filled", "bloom", "赛博"),
    free_theme("teaterminal", "茶褐终端", "茶褐对比｜呼吸终端", "cyber", "tea", "contrast", "quiet", "pulse", "赛博"),
    free_theme("goldwire", "金丝网格", "金丝描边｜金框网格", "cyber", "osmanthus", "outline", "gilt", "gilt", "赛博"),
    free_theme("voidpulse", "暗舱散光", "暗舱浅底｜散光指示", "cyber", "ink", "soft", "quiet", "bloom", "赛博"),
    free_theme("pinewash", "松绿泼墨", "松绿水洗｜晕墨层峦", "guofeng", "pine", "wash", "wash", "ink", "国风"),
    free_theme("inkseal", "青墨方印", "青墨朱印｜方印光晕", "guofeng", "ink", "seal", "seal", "glow", "国风"),
    free_theme("claywash", "陶土水墨", "陶土水洗｜素净留白", "guofeng", "clay", "wash", "quiet", "none", "国风"),
    free_theme("giltfan", "金扇细线", "金扇描边｜金框留白", "guofeng", "osmanthus", "classic", "gilt", "gilt", "国风"),
    free_theme("teascroll", "茶褐长卷", "茶褐水洗｜古风晕墨", "guofeng", "tea", "wash", "classic", "ink", "国风"),
    free_theme("mistshan", "远山淡墨", "远山描边｜淡墨留白", "guofeng", "mist", "outline", "wash", "none", "国风"),
    free_theme("stalltea", "茶摊灯火", "茶摊实心｜灯火光晕", "street", "tea", "fill", "ardent", "glow", "市井烟火"),
    free_theme("alleyink", "巷墨暖边", "巷墨热烈｜暖边微浮", "street", "ink", "ardent", "quiet", "lift", "市井烟火"),
    free_theme("bricklamp", "砖巷浅灯", "砖巷浅底｜暖边灯火", "street", "clay", "soft", "ardent", "none", "市井烟火"),
    free_theme("pinealley", "青瓦巷口", "青瓦热烈｜清新微浮", "street", "pine", "ardent", "fresh", "lift", "市井烟火"),
    free_theme("miststall", "雾夜摊牌", "雾夜实心｜薄雾灯火", "street", "mist", "fill", "fog", "glow", "市井烟火"),
    free_theme("goldstall", "金幌按压", "金幌热烈｜按压弹跳", "street", "osmanthus", "ardent", "gilt", "press", "市井烟火"),
    free_theme("springpine", "新岁松金", "新岁松绿｜金线清新", "festival", "pine", "gilt", "fresh", "gilt", "节日限定"),
    free_theme("teafest", "社戏茶印", "社戏茶褐｜朱印散光", "festival", "tea", "seal", "classic", "bloom", "节日限定"),
    free_theme("mistlantern", "纱灯雾金", "纱灯浅底｜雾金光晕", "festival", "mist", "soft", "gilt", "glow", "节日限定"),
    free_theme("inkyear", "岁墨朱印", "岁墨方印｜素净散光", "festival", "ink", "seal", "quiet", "bloom", "节日限定"),
    free_theme("clayfresh", "节庆陶土", "节庆陶土｜清新暖边", "festival", "clay", "fresh", "ardent", "none", "节日限定"),
    free_theme("osmanfill", "桂花实心", "桂花实键｜金框微浮", "festival", "osmanthus", "fill", "gilt", "lift", "节日限定"),
    free_theme("pixelfill", "像素实心", "像素实键｜细线按压", "anime", "mist", "fill", "line", "press", "二次元"),
    free_theme("starsoft", "星符浅底", "星符浅底｜金框呼吸", "anime", "osmanthus", "soft", "gilt", "pulse", "二次元"),
    free_theme("comicoutline", "漫页描边", "漫页细线｜浅填分格", "anime", "clay", "outline", "filled", "none", "二次元"),
    free_theme("inkpixel", "墨格广播", "墨格清新｜素净呼吸", "anime", "ink", "fresh", "quiet", "pulse", "二次元"),
    free_theme("teacomic", "茶褐漫格", "茶褐浅底｜古风按压", "anime", "tea", "soft", "classic", "press", "二次元"),
    free_theme("pineglyph", "青瓦星符", "青瓦金线｜清新光晕", "anime", "pine", "gilt", "fresh", "glow", "二次元"),
    free_theme("inkfill", "墨夜实心", "墨夜实键｜素净细线", "dark", "ink", "fill", "quiet", "none", "极简暗色"),
    free_theme("teacontrast", "炭火对比", "炭火墨色｜薄雾对比", "dark", "tea", "contrast", "fog", "none", "极简暗色"),
    free_theme("claydark", "暗窑深沉", "暗窑陶土｜深沉素净", "dark", "clay", "solemn", "quiet", "none", "极简暗色"),
    free_theme("osmandark", "暗金薄雾", "暗金雾面｜金框夜色", "dark", "osmanthus", "fog", "gilt", "none", "极简暗色"),
    free_theme("pinevoid", "夜田对比", "夜田松绿｜墨色对比", "dark", "pine", "contrast", "quiet", "none", "极简暗色"),
    free_theme("mistfog", "空雾暗角", "空雾雾面｜薄雾暗角", "dark", "mist", "fog", "fog", "none", "极简暗色"),
]


DECORATIONS = [
    {
        "decoration_id": "cards-plain",
        "name": "系统默认罐头卡",
        "desc": "罐头卡片跟随当前主题。",
        "cover_img": "cards",
        "style_json": {"borderRadius": "12px"},
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-plain",
        "name": "系统默认主页底",
        "desc": "个人主页背景跟随当前主题。",
        "cover_img": "profile",
        "style_json": {"background": "var(--page-color)"},
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-plain",
        "name": "系统默认头像框",
        "desc": "头像不加额外边框。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "0px"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-bubble-plain",
        "name": "系统默认评论气泡",
        "desc": "评论气泡跟随当前主题。",
        "cover_img": "comment",
        "style_json": {"borderRadius": "12px"},
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-paper",
        "name": "宣纸折边",
        "desc": "罐头卡片带宣纸折边和浅阴影。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "4px",
            "borderColor": "var(--border-color)",
            "shadow": "0 8rpx 20rpx var(--border-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-mist",
        "name": "江雾纹理",
        "desc": "个人中心底换成一层淡雾。",
        "cover_img": "profile",
        "style_json": {"background": "var(--surface-subtle-color)"},
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-frame",
        "name": "青瓦圆框",
        "desc": "头像外加一圈主题色青瓦框。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "4px", "borderColor": "var(--accent-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-paper",
        "name": "宣纸气泡",
        "desc": "评论气泡像一小张宣纸。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "4px",
            "background": "var(--surface-color)",
            "borderColor": "var(--border-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-brick",
        "name": "红砖压纹",
        "desc": "罐头卡片底带浅砖纹和陶土细边。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "2px",
            "borderWidth": "2px",
            "borderColor": "var(--accent-color)",
            "background": "var(--surface-subtle-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-round",
        "name": "软圆罐头卡",
        "desc": "罐头卡片收成更圆的软边。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "24px",
            "shadow": "0 12rpx 24rpx var(--border-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-night",
        "name": "夜航网格",
        "desc": "个人中心底换成夜航网格。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--surface-color)",
            "color": "var(--text-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-grain",
        "name": "田野浅纹",
        "desc": "个人中心底带一层浅田野纹。",
        "cover_img": "profile",
        "style_json": {"background": "var(--accent-subtle-color)"},
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-glyph",
        "name": "方言文字框",
        "desc": "头像框带一圈方言字。",
        "cover_img": "avatar",
        "style_json": {
            "borderWidth": "2px",
            "borderColor": "var(--accent-color)",
            "color": "var(--accent-color)",
        },
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-ink",
        "name": "青墨细框",
        "desc": "头像外加一圈青墨细线。",
        "cover_img": "avatar",
        "style_json": {
            "borderWidth": "6px",
            "borderColor": "var(--text-color)",
        },
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-round",
        "name": "软圆气泡",
        "desc": "评论气泡收成更圆的软边。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "24px",
            "background": "var(--surface-subtle-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-ink",
        "name": "青墨方泡",
        "desc": "评论气泡换成青墨细方框。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "0px",
            "borderColor": "var(--text-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "navbar-plain",
        "name": "系统默认顶栏",
        "desc": "导航栏跟随当前主题。小程序原生栏无法自定义。",
        "cover_img": "nav",
        "style_json": {"color": "var(--text-color)"},
        "component_type": ComponentType.NAV_BAR,
        "group": "navbar",
        "style_tags": ["导航栏"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5"],
    },
    {
        "decoration_id": "tabbar-plain",
        "name": "系统默认底栏",
        "desc": "底部 Tab 跟随当前主题。小程序原生栏无法自定义。",
        "cover_img": "tabbar",
        "style_json": {"background": "var(--surface-color)"},
        "component_type": ComponentType.TAB_BAR,
        "group": "tabbar",
        "style_tags": ["底部Tab"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5"],
    },
    {
        "decoration_id": "cards-member",
        "name": "会员宣纸卡",
        "desc": "会员专属罐头卡片纹理。",
        "cover_img": "cards",
        "style_json": {"borderColor": "var(--accent-color)"},
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.MEMBER,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-creator",
        "name": "方言达人头像框",
        "desc": "完成创作任务后领取。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "4px"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.CREATOR,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-sharp",
        "name": "方折罐头卡",
        "desc": "罐头卡片收成直角折边。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "0px",
            "borderWidth": "1px",
            "borderColor": "var(--text-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-wide",
        "name": "宽影罐头卡",
        "desc": "罐头卡片带更宽的浅阴影。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "16px",
            "shadow": "0 16rpx 32rpx var(--border-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-thin",
        "name": "细边罐头卡",
        "desc": "罐头卡片只留一圈细边。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "8px",
            "borderWidth": "1px",
            "borderColor": "var(--border-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-accent",
        "name": "浅彩罐头卡",
        "desc": "罐头卡片底换成浅强调色。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "12px",
            "background": "var(--accent-subtle-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-soft",
        "name": "雾底罐头卡",
        "desc": "罐头卡片底换成更软的浅底。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "20px",
            "background": "var(--surface-subtle-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-ridge",
        "name": "压线罐头卡",
        "desc": "罐头卡片外加一圈加厚压线。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "6px",
            "borderWidth": "3px",
            "borderColor": "var(--accent-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-wash",
        "name": "水墨浅底",
        "desc": "个人中心底换成一层水墨浅色。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--page-color)",
            "color": "var(--text-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-line",
        "name": "栏线主页",
        "desc": "个人中心底带一圈浅栏线。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--surface-color)",
            "borderColor": "var(--border-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-deep",
        "name": "深雾主页",
        "desc": "个人中心底换成更深一层淡雾。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--surface-subtle-color)",
            "color": "var(--text-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-glow",
        "name": "浅彩主页",
        "desc": "个人中心底换成浅强调色。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--accent-subtle-color)",
            "color": "var(--accent-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-fog",
        "name": "薄雾主页",
        "desc": "个人中心底换成更淡的页面底。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--page-color)",
            "color": "var(--muted-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-tile",
        "name": "青瓦主页",
        "desc": "个人中心底带一层青瓦浅纹。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--surface-color)",
            "borderColor": "var(--accent-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-thin",
        "name": "细线圆框",
        "desc": "头像外加一圈极细主题色。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "1px", "borderColor": "var(--accent-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-soft",
        "name": "浅彩宽框",
        "desc": "头像外加一圈更宽的浅彩框。",
        "cover_img": "avatar",
        "style_json": {
            "borderWidth": "8px",
            "borderColor": "var(--accent-subtle-color)",
        },
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-ridge",
        "name": "压线圆框",
        "desc": "头像外加一圈中等压线。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "3px", "borderColor": "var(--accent-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-mist",
        "name": "雾边圆框",
        "desc": "头像外加一圈浅雾边。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "2px", "borderColor": "var(--border-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-seal",
        "name": "朱印圆框",
        "desc": "头像外加一圈朱印色细框。",
        "cover_img": "avatar",
        "style_json": {
            "borderWidth": "4px",
            "borderColor": "var(--accent-color)",
            "color": "var(--text-color)",
        },
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-wide",
        "name": "宽墨圆框",
        "desc": "头像外加一圈更宽的墨框。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "10px", "borderColor": "var(--text-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-pill",
        "name": "胶囊气泡",
        "desc": "评论气泡收成更长的胶囊。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "32px",
            "background": "var(--accent-subtle-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-soft",
        "name": "浅底气泡",
        "desc": "评论气泡换成更软的浅底。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "16px",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-line",
        "name": "细线气泡",
        "desc": "评论气泡只留一圈细线。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "8px",
            "borderColor": "var(--border-color)",
            "background": "transparent",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-accent",
        "name": "浅彩气泡",
        "desc": "评论气泡底换成浅强调色。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "12px",
            "background": "var(--accent-subtle-color)",
            "borderColor": "var(--accent-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-square",
        "name": "小方气泡",
        "desc": "评论气泡收成小圆角方框。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "2px",
            "background": "var(--surface-subtle-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-fog",
        "name": "薄雾气泡",
        "desc": "评论气泡底换成一层薄雾。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "20px",
            "background": "var(--page-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
]


def seed_catalog():
    from .models import CatalogVersion, DecorationItem, ThemeItem

    for row in THEMES:
        ThemeItem.objects.update_or_create(theme_id=row["theme_id"], defaults=row)
    for row in DECORATIONS:
        DecorationItem.objects.update_or_create(
            decoration_id=row["decoration_id"], defaults=row
        )
    CatalogVersion.objects.get_or_create(pk=1, defaults={"value": 1})
