from .models import ComponentType, ItemStatus, PrivilegeType

THEMES = [
    {
        "theme_id": "default",
        "name": "默认方言主题",
        "desc": "乡野松绿｜统一导航、按钮和卡片配色",
        "cover_img": "default",
        "style_json": {
            "accent": "pine",
            "primaryLook": "fill",
            "ghostLook": "line",
            "effect": "none",
        },
        "style_tags": ["简约"],
        "dialect_tags": [],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "paper",
        "name": "素白纸本",
        "desc": "田野笔记｜浅底细线、留白克制",
        "cover_img": "simple",
        "style_json": {"accent": "pine", "primaryLook": "line", "ghostLook": "line"},
        "style_tags": ["简约"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "member-pine",
        "name": "松风会员",
        "desc": "会员专属｜松绿细纹",
        "cover_img": "simple",
        "style_json": {"accent": "pine", "primaryLook": "fill"},
        "style_tags": ["简约"],
        "privilege_type": PrivilegeType.MEMBER,
        "get_condition": "开通会员后可启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "event-lantern",
        "name": "同乡灯会",
        "desc": "活动限定｜同乡灯火",
        "cover_img": "street",
        "style_json": {"accent": "clay", "effect": "none"},
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.ACTIVITY,
        "get_condition": "限时同乡灯会产出",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "event-spring",
        "name": "开春乡音",
        "desc": "活动已结束｜已绝版",
        "cover_img": "festival",
        "style_json": {"accent": "clay"},
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.ACTIVITY,
        "get_condition": "活动已结束",
        "status": ItemStatus.DEPRECATED,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "creator-tile",
        "name": "方言达人青瓦",
        "desc": "创作者专属｜青瓦细纹",
        "cover_img": "guofeng",
        "style_json": {"accent": "pine"},
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.CREATOR,
        "get_condition": "完成方言创作任务后领取",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "chuankiang",
        "name": "川渝烟火",
        "desc": "巴蜀市井热辣风格",
        "cover_img": "dialect",
        "style_json": {"accent": "clay"},
        "style_tags": ["地域方言风"],
        "dialect_tags": ["川渝"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "敬请期待",
        "status": ItemStatus.COMING,
        "support_terminal": ["h5", "miniprogram"],
    },
]


DECORATIONS = [
    {
        "decoration_id": "cards-plain",
        "name": "系统默认罐头卡",
        "desc": "罐头卡片跟随当前主题。",
        "cover_img": "cards",
        "style_json": {"borderRadius": "12px"},
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-plain",
        "name": "系统默认主页底",
        "desc": "个人主页背景跟随当前主题。",
        "cover_img": "profile",
        "style_json": {"background": "var(--page-color)"},
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-plain",
        "name": "系统默认头像框",
        "desc": "头像不加额外边框。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "0px"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-bubble-plain",
        "name": "系统默认评论气泡",
        "desc": "评论气泡跟随当前主题。",
        "cover_img": "comment",
        "style_json": {"borderRadius": "12px"},
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "navbar-plain",
        "name": "系统默认顶栏",
        "desc": "导航栏跟随当前主题。小程序原生栏无法自定义。",
        "cover_img": "nav",
        "style_json": {"color": "var(--text-color)"},
        "component_type": ComponentType.NAV_BAR,
        "group": "navbar",
        "style_tags": ["导航栏"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5"],
    },
    {
        "decoration_id": "tabbar-plain",
        "name": "系统默认底栏",
        "desc": "底部 Tab 跟随当前主题。小程序原生栏无法自定义。",
        "cover_img": "tabbar",
        "style_json": {"background": "var(--surface-color)"},
        "component_type": ComponentType.TAB_BAR,
        "group": "tabbar",
        "style_tags": ["底部Tab"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5"],
    },
    {
        "decoration_id": "cards-member",
        "name": "会员宣纸卡",
        "desc": "会员专属罐头卡片纹理。",
        "cover_img": "cards",
        "style_json": {"borderColor": "var(--accent-color)"},
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.MEMBER,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-creator",
        "name": "方言达人头像框",
        "desc": "完成创作任务后领取。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "4px"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.CREATOR,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
]


def seed_catalog():
    from .models import CatalogVersion, DecorationItem, ThemeItem

    for row in THEMES:
        ThemeItem.objects.update_or_create(theme_id=row["theme_id"], defaults=row)
    for row in DECORATIONS:
        DecorationItem.objects.update_or_create(
            decoration_id=row["decoration_id"], defaults=row
        )
    CatalogVersion.objects.get_or_create(pk=1, defaults={"value": 1})
